# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Sql_Test
DESTDIR = ../x64/Debug
QT += core sql gui widgets
CONFIG += debug console
DEFINES += _UNICODE WIN64 QT_DLL QT_SQL_LIB QT_WIDGETS_LIB
INCLUDEPATH += ./GeneratedFiles \
    . \
    ./GeneratedFiles/$(ConfigurationName)
DEPENDPATH += .
MOC_DIR += ./GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
INCLUDEPATH += C:\Program Files\MySQL\Connector.C++ 1.1\include
LIBS += -LC:\Program Files\MySQL\Connector.C++ 1.1\lib -llibmysql

FORMS += \
    Sql_Test.ui

HEADERS += \
    Sql_Test.h

SOURCES += \
    Sql_Test.cpp \
    main.cpp
